name: Build Jekyll site
on:
 pull_request_review:
    types: [submitted, edited]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
