name: Build Jekyll site
on:
 push:
   branches: ["main"]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1s